"""TDD test generator — comprehend an API, emit the tests that prove the integration.

Point it at any OpenAPI spec; it generates first-call-correctness checks for every tool
the agent can actually use and runs them in ``recorded`` mode (offline, $0) — so you verify
the integration *before* a single live call. Two faces:

- ``check(spec)`` runs the checks in-process and returns a report (use as a gate / CI step).
- ``render_module(spec)`` emits a standalone pytest module to commit to your repo.

Each usable tool gets two checks:
1. **well-formed first call** — synthesized valid args produce a 200 with data (recorded).
2. **required-field guard** — dropping a required field is caught locally (``CallError``),
   not fired as a malformed call.

The tests are a pure function of the comprehended surface — regenerate when the API drifts.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from .access import AuthSession
from .caller import CallError
from .client import AgentApiClient
from .sample import example_from_schema

_OK_STATUS = (200, 201)


@dataclass(frozen=True)
class CaseResult:
    tool: str
    kind: str  # "well_formed" | "required_guard"
    ok: bool
    detail: str


def _required(tool: dict[str, Any]) -> list[str]:
    schema = tool.get("inputSchema") or {}
    return list(schema.get("required") or [])


def _args_for(tool: dict[str, Any]) -> dict[str, Any]:
    args = example_from_schema(tool.get("inputSchema") or {})
    return args if isinstance(args, dict) else {}


def check(
    spec: str | dict[str, Any],
    *,
    mode: str = "recorded",
    base_url: str | None = None,
    session: AuthSession | None = None,
) -> list[CaseResult]:
    """Comprehend ``spec``, then run first-call-correctness checks for every usable tool."""
    client = AgentApiClient(spec, base_url=base_url, session=session)
    results: list[CaseResult] = []
    for tool in client.list_tools():
        name = tool["name"]
        args = _args_for(tool)

        # 1) well-formed first call → 200 + data (recorded synthesis from the schema)
        try:
            resp = client.call(name, args, mode=mode)
            ok = resp.get("status") in _OK_STATUS and "data" in resp
            results.append(
                CaseResult(name, "well_formed", ok, f"status={resp.get('status')}")
            )
        except Exception as exc:  # noqa: BLE001 - report it, don't crash the run
            results.append(
                CaseResult(name, "well_formed", False, f"{type(exc).__name__}: {exc}")
            )

        # 2) required-field guard → dropping a required field is caught locally
        req = _required(tool)
        if req:
            drop = req[0]
            bad = {k: v for k, v in args.items() if k != drop}
            try:
                client.call(name, bad, mode=mode)
                results.append(
                    CaseResult(
                        name, "required_guard", False, f"missing '{drop}' NOT caught"
                    )
                )
            except CallError:
                results.append(
                    CaseResult(name, "required_guard", True, f"missing '{drop}' caught")
                )
            except Exception as exc:  # noqa: BLE001
                results.append(
                    CaseResult(
                        name, "required_guard", False, f"{type(exc).__name__}: {exc}"
                    )
                )
    return results


def summary(results: list[CaseResult]) -> tuple[int, int]:
    """(passed, total)."""
    return sum(1 for r in results if r.ok), len(results)


_MODULE_TEMPLATE = '''\
"""AUTO-GENERATED by gecko-surf testgen — first-call-correctness tests for this API.

Run offline ($0):   uv run pytest __OUT__
Run live:           GECKO_MODE=live uv run pytest __OUT__   (needs a real session/base_url)

These prove the integration is first-call-correct BEFORE you go live. The tests are a pure
function of the comprehended surface — regenerate when the API drifts.
"""

import os

import pytest

from gecko.caller import CallError
from gecko.client import AgentApiClient
from gecko.sample import example_from_schema

SPEC = __SPEC_REPR__
MODE = os.environ.get("GECKO_MODE", "recorded")
_client = AgentApiClient(SPEC)
_TOOLS = {t["name"]: t for t in _client.list_tools()}
_REQUIRED = [n for n, t in _TOOLS.items() if (t.get("inputSchema") or {}).get("required")]


@pytest.mark.parametrize("name", list(_TOOLS))
def test_first_call_well_formed(name):
    """Synthesized valid args -> a well-formed first call (200 + data)."""
    args = example_from_schema(_TOOLS[name].get("inputSchema") or {}) or {}
    resp = _client.call(name, args if isinstance(args, dict) else {}, mode=MODE)
    assert resp.get("status") in (200, 201), f"{name}: status {resp.get('status')}"
    assert "data" in resp


@pytest.mark.parametrize("name", _REQUIRED)
def test_missing_required_is_caught(name):
    """Dropping a required field is caught locally (CallError), not fired."""
    schema = _TOOLS[name].get("inputSchema") or {}
    full = example_from_schema(schema) or {}
    drop = schema["required"][0]
    bad = {k: v for k, v in full.items() if k != drop}
    with pytest.raises(CallError):
        _client.call(name, bad, mode=MODE)
'''


def render_module(spec_ref: str, *, out_name: str = "test_api_firstcall.py") -> str:
    """Emit a standalone pytest module (commit it to your repo / CI)."""
    return _MODULE_TEMPLATE.replace("__SPEC_REPR__", repr(spec_ref)).replace(
        "__OUT__", out_name
    )


def _run() -> None:  # CLI: gecko-testgen <spec> [-o out.py]
    import sys

    argv = sys.argv[1:]
    if not argv:
        print("usage: gecko-testgen <openapi-url-or-path> [-o out.py]", file=sys.stderr)
        raise SystemExit(2)
    spec_ref = argv[0]
    out = argv[argv.index("-o") + 1] if "-o" in argv else None

    results = check(spec_ref)
    for r in results:
        print(f"  [{'PASS' if r.ok else 'FAIL'}] {r.tool} · {r.kind} — {r.detail}")
    passed, total = summary(results)
    print(f"\n{passed}/{total} checks passed (recorded mode)")

    if out:
        with open(out, "w", encoding="utf-8") as fh:
            fh.write(render_module(spec_ref, out_name=out))
        print(f"wrote pytest module -> {out}")

    raise SystemExit(0 if passed == total else 1)


if __name__ == "__main__":
    _run()
