"""Candidate operations -> a *draft* OpenAPI 3.1 document.

Reuses the JSON-RPC modeling convention from ``examples/jito/`` (hand-authored):
each JSON-RPC method becomes its own question-shaped operation at a virtual
``/{operationId}`` route, with the true wire target on ``x-jsonrpc-endpoint``, the
envelope method on ``x-jsonrpc-method``, and the positional order on
``x-jsonrpc-params``. REST ops carry ``x-transport: rest`` + ``x-endpoint-url``.

This is the on-ramp output, not a shipped spec: every field the parser was unsure
of is marked ``x-draft-confidence`` and, where a human must act, ``x-review``. The
doc is honest by construction — a reader can see exactly what to confirm.

Productized from ``spikes/docs_reader/emit.py``.
"""

from __future__ import annotations

from typing import Any

from .models import CandidateOp, CandidateParam

_DRAFT_NOTE = (
    "DRAFT auto-generated by Gecko docs_reader from a rendered docs site. "
    "JSON-RPC methods are surfaced as individual operations (virtual /{method} "
    "routes); the wire target is on x-jsonrpc-endpoint/x-jsonrpc-method and the "
    "positional envelope order on x-jsonrpc-params. Fields marked x-draft-confidence "
    "'low' or carrying x-review need human confirmation before this is trusted."
)


def _param_schema(param: CandidateParam) -> dict[str, Any]:
    schema: dict[str, Any] = {"type": param.type}
    if param.type == "array":
        schema["items"] = {"type": "string"}
    if param.enum:
        schema["enum"] = param.enum
    if param.default is not None:
        schema["default"] = param.default
    if param.description:
        schema["description"] = param.description
    if param.confidence != "high":
        schema["x-draft-confidence"] = param.confidence
    if param.review:
        schema["x-review"] = param.review
    return schema


def _request_body(op: CandidateOp) -> dict[str, Any] | None:
    body_params = [p for p in op.params if p.location == "body"]
    if not body_params:
        return None
    properties = {p.name: _param_schema(p) for p in body_params}
    required = [p.name for p in body_params if p.required]
    schema: dict[str, Any] = {"type": "object", "properties": properties}
    if required:
        schema["required"] = required
    return {
        "required": bool(required),
        "content": {"application/json": {"schema": schema}},
    }


def _responses(op: CandidateOp) -> dict[str, Any]:
    schema: dict[str, Any] = {"type": "object"}
    if op.response_example is not None:
        # Permissive schema; the example lets recorded mode return something real.
        schema = {
            "type": _example_type(op.response_example),
            "example": op.response_example,
        }
    return {
        "200": {
            "description": "Recovered from the docs response example (draft).",
            "content": {"application/json": {"schema": schema}},
        }
    }


def _example_type(value: Any) -> str:
    if isinstance(value, list):
        return "array"
    if isinstance(value, dict):
        return "object"
    return "string"


def _operation_object(op: CandidateOp) -> dict[str, Any]:
    obj: dict[str, Any] = {
        "operationId": op.operation_id,
        "summary": op.summary,
        "x-draft-confidence": op.confidence,
        "responses": _responses(op),
    }
    if op.review:
        obj["x-review"] = op.review
    if op.transport == "jsonrpc":
        obj["x-jsonrpc-method"] = op.jsonrpc_method
        obj["x-jsonrpc-endpoint"] = op.http_path
        obj["x-jsonrpc-params"] = [p.name for p in op.params]
        obj["tags"] = ["jsonrpc"]
    else:
        obj["x-transport"] = "rest"
        obj["x-endpoint-url"] = op.host.rstrip("/") + op.http_path
        obj["tags"] = ["rest"]
    body = _request_body(op)
    if body is not None:
        obj["requestBody"] = body
    query_params = [p for p in op.params if p.location == "query"]
    if query_params:
        obj["parameters"] = [
            {
                "name": p.name,
                "in": "query",
                "required": p.required,
                "schema": _param_schema(p),
            }
            for p in query_params
        ]
    return obj


def build_draft_openapi(
    ops: list[CandidateOp],
    title: str,
    source_urls: list[str],
    uuid_auth: dict[str, str] | None = None,
) -> dict[str, Any]:
    """Assemble the draft spec. ``uuid_auth`` (if recovered) adds an OPTIONAL scheme."""
    # Distinct hosts, JSON-RPC (POST) host first so servers[0] is the primary target.
    hosts: list[str] = []
    for op in sorted(ops, key=lambda o: o.transport != "jsonrpc"):
        if op.host and op.host not in hosts:
            hosts.append(op.host)

    paths: dict[str, Any] = {}
    for op in ops:
        route = f"/{op.operation_id}"
        http_method = op.http_method.lower()
        paths[route] = {http_method: _operation_object(op)}

    doc: dict[str, Any] = {
        "openapi": "3.1.0",
        "info": {
            "title": title,
            "version": "0.1.0-draft",
            "description": _DRAFT_NOTE,
            "x-source": source_urls,
            "x-generated-by": "gecko.docs_reader",
        },
        "servers": [{"url": h} for h in hosts] or [{"url": ""}],
        "paths": paths,
    }
    if any(op.transport == "jsonrpc" for op in ops):
        doc["x-jsonrpc"] = {
            "version": "2.0",
            "note": (
                "Virtual /{method} paths give each JSON-RPC method its own operation. "
                "Live transport POSTs {jsonrpc, id, method: x-jsonrpc-method, params: "
                "requestBody fields in x-jsonrpc-params order} to x-jsonrpc-endpoint."
            ),
        }
    if uuid_auth is not None:
        doc.setdefault("components", {})["securitySchemes"] = {
            "uuidAuth": {
                "type": "apiKey",
                "in": uuid_auth["in"],
                "name": uuid_auth["name"],
                "description": (
                    "OPTIONAL UUID for higher rate limits (recovered from docs auth "
                    "note). Injected by the access layer, never surfaced to the agent."
                ),
            }
        }
        # Optional on every op: {} means 'no auth also works' (invariant: agent-invisible).
        for route in doc["paths"].values():
            for op_obj in route.values():
                op_obj["security"] = [{}, {"uuidAuth": []}]
    return doc
