"""AUTO-GENERATED by gecko-surf testgen — first-call-correctness tests for this API.

Run offline ($0):   uv run pytest examples/charge_before_live/test_payapi_firstcall.py
Run live:           GECKO_MODE=live uv run pytest examples/charge_before_live/test_payapi_firstcall.py   (needs a real session/base_url)

These prove the integration is first-call-correct BEFORE you go live. The tests are a pure
function of the comprehended surface — regenerate when the API drifts.
"""

import os

import pytest

from gecko.caller import CallError
from gecko.client import AgentApiClient
from gecko.sample import example_from_schema

SPEC = "examples/charge_before_live/spec/payapi_openapi.json"
MODE = os.environ.get("GECKO_MODE", "recorded")
_client = AgentApiClient(SPEC)
_TOOLS = {t["name"]: t for t in _client.list_tools()}
_REQUIRED = [
    n for n, t in _TOOLS.items() if (t.get("inputSchema") or {}).get("required")
]


@pytest.mark.parametrize("name", list(_TOOLS))
def test_first_call_well_formed(name):
    """Synthesized valid args -> a well-formed first call (200 + data)."""
    args = example_from_schema(_TOOLS[name].get("inputSchema") or {}) or {}
    resp = _client.call(name, args if isinstance(args, dict) else {}, mode=MODE)
    assert resp.get("status") in (200, 201), f"{name}: status {resp.get('status')}"
    assert "data" in resp


@pytest.mark.parametrize("name", _REQUIRED)
def test_missing_required_is_caught(name):
    """Dropping a required field is caught locally (CallError), not fired."""
    schema = _TOOLS[name].get("inputSchema") or {}
    full = example_from_schema(schema) or {}
    drop = schema["required"][0]
    bad = {k: v for k, v in full.items() if k != drop}
    with pytest.raises(CallError):
        _client.call(name, bad, mode=MODE)
